output "application_url" {
  value       = module.application.application_url
  description = "The Web application URL."
}

output "resource_group" {
  value       = azurerm_resource_group.main.name
  description = "The resource group."
}

output "application_name" {
  value       = module.application.application_caf_name
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "storage_account_name" {
  value       = module.storage_account.storage_account_name
  description = "The name of the storage account."
}

output "azure_storage_connection_string" {
  description = "Azure Storage Connection String"
  value       = "DefaultEndpointsProtocol=https;AccountName=${azurerm_storage_account.storage.name};AccountKey=${azurerm_storage_account.storage.primary_access_key};EndpointSuffix=core.windows.net"
  sensitive   = true
}